platform :ios, '8.0'
use_frameworks!

target 'FirebaseRxSwiftExtensions_Example' do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end

target 'FirebaseRxSwiftExtensions_Tests' do
  pod "FirebaseRxSwiftExtensions", :path => "../"
end
